### ISSUE TITLE
Download Fortify ScanCentral Client failed - Expand-Archive : is not a supported archive file format. .zip is the only supported archive file format

### ISSUE THREAD

**Issue by dobromirtt1** [fortify/gha-setup-scancentral-client#23]
Set up  Fortify ScanCentral Client task for ScanCentral download client is failing in GitHub with error: Expand-Archive : is not a supported archive file format. .zip is the only supported archive file format.

**Task used in Yml:**

### Set up Fortify ScanCentral Client ###
      - name: Download Fortify ScanCentral Client
        uses: fortify/gha-setup-scancentral-client@v1   
        with:
          version: 21.2.0   

How to set up correctly and download Fortify ScanCentral Client? What should be correct yml file. Thank you for assistance.

**Comment by rsenden** [comment]
This seems to be an issue with the GitHub tool-cache module, so I've opened a bug report at https://github.com/actions/toolkit/issues/1179.

Can you please provide details on what runner you are using (Windows/Linux, standard GitHub runner or custom runner, ...) and/or share your full GitHub workflow yaml file, either here or by commenting on the toolkit issue listed above?

**Comment by dobromirtt1** [comment]
Thanks for reply. It is Windows 11 runner [self-hosted, Windows, x64].

Used Yaml is same as in Usage part of guide: https://github.com/fortify/gha-setup-scancentral-client#usage. Only difference is **runs-on: self-hosted**

**Yaml Example 1:**

name: Fortify ScanCentral SAST Scan
on:
  workflow_dispatch:
  push:
    # Master or main branch that you want to trigger this workflow for
    branches: [master]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [master]

jobs:                                                  
  Fortify-SAST:
    # Use the appropriate runner for building your source code
    runs-on: self-hosted

    steps:
      # Check out source code
      - name: Check Out Source Code
        uses: actions/checkout@v2
        with:
          # Fetch at least the immediate parents so that if this is a pull request then we can checkout the head.
          fetch-depth: 2
      # If this run was triggered by a pull request event, then checkout the head of the pull request instead of the merge commit.
      - run: git checkout HEAD^2
        if: ${{ github.event_name == 'pull_request' }} 

      # Java is required to run ScanCentral Client, and may be required for your build
      # Java version to use depends on the Java version required to run your build (if any),
      # and the Java version supported by the ScanCentral Client version that you are running
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 11

      ### Set up Fortify ScanCentral Client ###
      - name: Download Fortify ScanCentral Client
        uses: fortify/gha-setup-scancentral-client@v1   
        with:
          version: 21.2.0  

** Yaml Example 2:**

name: Fortify ScanCentral SAST Scan
on:
  workflow_dispatch:
  push:
    # Master or main branch that you want to trigger this workflow for
    branches: [master]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [master]

jobs:                                                  
  Fortify-SAST:
    # Use the appropriate runner for building your source code
    runs-on: self-hosted

    steps:
      # Check out source code
      - name: Check Out Source Code
        uses: actions/checkout@v2
        with:
          # Fetch at least the immediate parents so that if this is a pull request then we can checkout the head.
          fetch-depth: 2
      # If this run was triggered by a pull request event, then checkout the head of the pull request instead of the merge commit.
      - run: git checkout HEAD^2
        if: ${{ github.event_name == 'pull_request' }} 

       ### Set up Fortify ScanCentral Client ###
      - name: Download Fortify ScanCentral Client
        uses: fortify/gha-setup-scancentral-client@v1   
        with:
          version: 21.2.0

**Comment by dobromirtt1** [comment]
@rsenden 
May I ask if there is any workaround for now? Thank you.

**Comment by dobromirtt1** [comment]
@rsenden 
Yes, it works. May I ask if we need to use uses: fortify/gha-setup-scancentral-client@master in future? Where are these repositories: master & v1? Thank you.

**Comment by rsenden** [comment]
Everything after the `@` sign refers to a branch or tag in the repository, so `@master` points to the `master` branch (holding the latest, possibly unreleased code changes), `@v1` points to the `v1` tag, ...

Branches are unstable; their contents could change at any time, they may sometimes be non-functional, or they may contain breaking changes. So, unless explicitly instructed to refer to a branch (for example like in this case, to test whether a particular fix works before publishing it as an official release), workflows should only reference published versions.

As for version tags, these follow semantic versioning, providing the following tags:

- `v<x>.<y>.<z>` pointing explicitly to a particular version
- `v<x>.<y>` pointing to the latest fix version `<z>` within this `<x>.<y>` range
- `v<x>` pointing to the latest feature or fix version `<y>.<z>` within this `<x>` range

As an example, I have now published a new `v2.2.1` version that includes the fix for this particular issue, as can be seen here: https://github.com/fortify/gha-setup-scancentral-client/releases. The `v2.2` and `v2` tags have also been updated to point to this latest release.

So, in order to use this fix, you'd need to use either `@v2`, `@v2.2` or `@v2.2.1`. Which one to use depends on the amount of stability that you want; `@v2.2.1` is the most stable as it will never change, but you won't benefit from any future bug fixes or backward-compatible features. With `@v2.2`, you would automatically get new bug fixes but not features, and with `@v2` you'd get both new bug fixes and backward-compatible features. If any breaking changes are introduced, this would be released as `v3.y.z`, so you'd need to explicitly update the workflow to use a `v3` version.

For simplicity, most customers would just use the major version number, so `v2` in this case, unless they prefer stability over agility.

Note that `v1` is still available but should be considered outdated as it is no longer being updated.
